# Site settings
author: Hanna Lee
title: Hanna
header-img: img/home-bg.png
email: mani21na@gmail.com
copyright_name: Hanna Lee
description: > # this means to ignore newlines until "baseurl:"
  about learning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mani21na

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
